In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()
os.chdir('a:\\Dominic\\My Projects\\Home Credit\\')

In [3]:
Loans = pd.read_csv('data/Internal/application_train.csv')

In [5]:
Loans.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
PrevLoans = pd.read_csv('data/Internal/previous_application.csv')

In [7]:
PrevLoans.head(100)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1851241,415052,Consumer loans,9675.855,46476.0,48775.5,0.0,46476.0,TUESDAY,16,...,Consumer electronics,6.0,high,POS household with interest,365243.0,-1337.0,-1187.0,-1187.0,-1181.0,0.0
96,2030030,133853,Consumer loans,7253.055,104809.5,121410.0,0.0,104809.5,SATURDAY,14,...,Consumer electronics,18.0,low_action,POS household without interest,365243.0,-315.0,195.0,365243.0,365243.0,0.0
97,1935914,191576,Consumer loans,NaN,23400.0,23400.0,NaN,23400.0,SATURDAY,9,...,Consumer electronics,NaN,XNA,POS household with interest,NaN,NaN,NaN,NaN,NaN,NaN
98,1457539,307992,Consumer loans,NaN,113215.5,113215.5,0.0,113215.5,SUNDAY,12,...,Connectivity,NaN,XNA,POS mobile with interest,NaN,NaN,NaN,NaN,NaN,NaN
99,1077629,203467,Cash loans,46345.320,1012500.0,1115410.5,NaN,1012500.0,THURSDAY,10,...,XNA,42.0,middle,Cash X-Sell: middle,365243.0,-944.0,286.0,-554.0,-551.0,1.0

In [8]:
PrevLoans.shape

(1670214, 37)

In [9]:
PrevLoans

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,Furniture,30.0,low_normal,POS industry with interest,365243.0,-508.0,362.0,-358.0,-351.0,0.0
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,Furniture,12.0,middle,POS industry with interest,365243.0,-1604.0,-1274.0,-1304.0,-1297.0,0.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

In [10]:
PrevLoans = PrevLoans.astype({'SK_ID_CURR': 'string', 'SK_ID_PREV': 'string'})
PrevLoans.dtypes

SK_ID_PREV                     string[python]
SK_ID_CURR                     string[python]
NAME_CONTRACT_TYPE                     object
AMT_ANNUITY                           float64
AMT_APPLICATION                       float64
AMT_CREDIT                            float64
AMT_DOWN_PAYMENT                      float64
AMT_GOODS_PRICE                       float64
WEEKDAY_APPR_PROCESS_START             object
HOUR_APPR_PROCESS_START                 int64
FLAG_LAST_APPL_PER_CONTRACT            object
NFLAG_LAST_APPL_IN_DAY                  int64
RATE_DOWN_PAYMENT                     float64
RATE_INTEREST_PRIMARY                 float64
RATE_INTEREST_PRIVILEGED              float64
NAME_CASH_LOAN_PURPOSE                 object
NAME_CONTRACT_STATUS                   object
DAYS_DECISION                           int64
NAME_PAYMENT_TYPE                      object
CODE_REJECT_REASON                     object
NAME_TYPE_SUITE                        object
NAME_CLIENT_TYPE                       object
NAME_GOODS_CATEGORY                    object
NAME_PORTFOLIO                         object
NAME_PRODUCT_TYPE                      object
CHANNEL_TYPE                           object
SELLERPLACE_AREA                        int64
NAME_SELLER_INDUSTRY                   object
CNT_PAYMENT                           float64
NAME_YIELD_GROUP                       object
PRODUCT_COMBINATION                    object
DAYS_FIRST_DRAWING                    float64
DAYS_FIRST_DUE                        float64
DAYS_LAST_DUE_1ST_VERSION             float64
DAYS_LAST_DUE                         float64
DAYS_TERMINATION                      float64
NFLAG_INSURED_ON_APPROVAL             float64
dtype: object

In [12]:
# PrevLoans.sort_values(by=['SK_ID_CURR', 'SK_ID_PREV'], inplace=True)
PrevLoans.sort_values(by=['SK_ID_CURR', 'DAYS_DECISION'], ascending=[True, False], inplace=True)

In [13]:
PrevLoans['NAME_CONTRACT_TYPE'].value_counts(dropna=False)

NAME_CONTRACT_TYPE
Cash loans         747553
Consumer loans     729151
Revolving loans    193164
XNA                   346
Name: count, dtype: int64

In [12]:
PrevLoans['NAME_CONTRACT_STATUS'].value_counts(dropna=False)

NAME_CONTRACT_STATUS
Approved        1036781
Canceled         316319
Refused          290678
Unused offer      26436
Name: count, dtype: int64

In [13]:
PrevLoans[(PrevLoans['AMT_CREDIT']==0) & (PrevLoans['NAME_CONTRACT_STATUS']=='Approved')]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
692071,2313600,101136,Revolving loans,0.0,0.0,0.0,NaN,0.0,WEDNESDAY,17,...,Consumer electronics,0.0,XNA,Card Street,-193.0,365243.0,365243.0,365243.0,365243.0,0.0
1160277,2575385,101196,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,13,...,Consumer electronics,0.0,XNA,Card Street,-90.0,365243.0,365243.0,365243.0,365243.0,0.0
1056809,1081051,101622,Revolving loans,0.0,0.0,0.0,NaN,0.0,MONDAY,12,...,Consumer electronics,0.0,XNA,Card Street,-241.0,-201.0,365243.0,-140.0,-101.0,0.0
1105923,1666991,101669,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,19,...,Connectivity,0.0,XNA,Card Street,-338.0,365243.0,365243.0,365243.0,365243.0,0.0
588884,2824785,101734,Revolving loans,0.0,0.0,0.0,NaN,0.0,SATURDAY,15,...,Consumer electronics,0.0,XNA,Card Street,-332.0,365243.0,365243.0,365243.0,365243.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548767,2780308,455312,Revolving loans,0.0,0.0,0.0,NaN,0.0,THURSDAY,11,...,Connectivity,0.0,XNA,Card Street,-279.0,365243.0,365243.0,365243.0,365243.0,0.0
13335,2272045,455494,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,9,...,Consumer electronics,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0
1012354,2697654,455539,Revolving loans,0.0,0.0,0.0,NaN,0.0,MONDAY,11,...,Consumer electronics,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0
1300855,1053330,455720,Revolving loans,0.0,0.0,0.0,NaN,0.0,SATURDAY,8,...,Connectivity,0.0,XNA,Card Street,-240.0,365243.0,365243.0,365243.0,365243.0,0.0
779847,1209934,456013,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,13,...,Consumer electronics,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0

In [14]:
PrevLoans[(PrevLoans['AMT_CREDIT'].isna()) & (PrevLoans['NAME_CONTRACT_STATUS']=='Approved')]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1127152,2204450,438387,Revolving loans,0.0,0.0,NaN,NaN,NaN,FRIDAY,10,...,Connectivity,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Refused'][PrevLoans['AMT_CREDIT']>=0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_39972\3234085287.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Refused'][PrevLoans['AMT_CREDIT']>=0]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1607443,1697039,100006,Cash loans,32696.100,688500.000,906615.000,NaN,688500.000,THURSDAY,15,...,XNA,48.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
268783,2668005,100011,Cash loans,NaN,0.000,0.000,NaN,0.000,WEDNESDAY,9,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
35014,2531618,100027,Cash loans,22556.475,225000.000,239850.000,NaN,225000.000,SATURDAY,14,...,XNA,12.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
780467,1625550,100030,Consumer loans,NaN,21969.225,21969.225,0.0,21969.225,SATURDAY,13,...,Connectivity,NaN,XNA,POS mobile with interest,NaN,NaN,NaN,NaN,NaN,NaN
1312908,1354305,100030,Consumer loans,6014.835,33561.000,27954.000,6714.0,33561.000,SUNDAY,15,...,Connectivity,5.0,low_normal,POS mobile without interest,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749319,2390857,456247,Consumer loans,NaN,52510.500,52510.500,0.0,52510.500,SUNDAY,13,...,Connectivity,NaN,XNA,POS mobile with interest,NaN,NaN,NaN,NaN,NaN,NaN
234061,2669123,456249,Consumer loans,11497.500,114210.000,125518.500,0.0,114210.000,WEDNESDAY,11,...,Consumer electronics,12.0,low_action,POS household without interest,NaN,NaN,NaN,NaN,NaN,NaN
1440475,2626069,456250,Cash loans,19151.100,450000.000,533160.000,NaN,450000.000,THURSDAY,7,...,XNA,48.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
814647,1296007,456255,Cash loans,30737.655,765000.000,1067940.000,NaN,765000.000,FRIDAY,14,...,XNA,60.0,low_normal,Cash Street: low,NaN,NaN,NaN,NaN,NaN,NaN
729432,1708056,456255,Revolving loans,2250.000,45000.000,45000.000,NaN,45000.000,SUNDAY,14,...,Connectivity,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']>0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_39972\1024469317.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']>0]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1064064,2237361,100038,Cash loans,24463.710,454500.0,508495.5,NaN,454500.0,TUESDAY,7,...,XNA,36.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
888028,1227828,100062,Cash loans,26316.000,900000.0,900000.0,NaN,900000.0,TUESDAY,19,...,XNA,60.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
1132970,1475898,100072,Cash loans,76091.760,1467000.0,1467000.0,NaN,1467000.0,THURSDAY,11,...,XNA,24.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
440306,1712955,100086,Cash loans,21775.500,675000.0,675000.0,NaN,675000.0,SATURDAY,14,...,XNA,60.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
1613283,2487942,100189,Cash loans,25475.625,562500.0,562500.0,NaN,562500.0,MONDAY,17,...,Furniture,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199606,1357202,456063,Cash loans,48334.950,810000.0,865597.5,NaN,810000.0,MONDAY,8,...,XNA,24.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
1363215,2619866,456079,Cash loans,50197.770,1354500.0,1354500.0,NaN,1354500.0,SATURDAY,15,...,XNA,36.0,low_action,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
469973,1971829,456088,Cash loans,30570.750,675000.0,675000.0,NaN,675000.0,FRIDAY,12,...,XNA,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
1642212,2626164,456186,Cash loans,27193.500,450000.0,450000.0,NaN,450000.0,WEDNESDAY,12,...,XNA,36.0,high,Cash X-Sell: high,NaN,NaN,NaN,NaN,NaN,NaN
565083,2355581,456235,Cash loans,12377.610,265500.0,265500.0,NaN,265500.0,THURSDAY,11,...,XNA,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']==0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_39972\3749386403.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']==0]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1259112,1857999,100005,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,10,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
617859,2827850,100006,Revolving loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
1232752,1243599,100006,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1595430,2545789,100006,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
600145,1757431,100008,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,18,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882795,1842078,456244,Cash loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,12,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1472002,1842431,456244,Cash loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,12,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1094543,1482581,456250,Revolving loans,NaN,0.0,0.0,NaN,NaN,MONDAY,11,...,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
1345759,2624169,456250,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,8,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
553648,1511244,456250,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,7,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
PrevLoans.loc[PrevLoans['DAYS_FIRST_DRAWING']==365243, 'DAYS_FIRST_DRAWING'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_FIRST_DUE']==365243, 'DAYS_FIRST_DUE'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_LAST_DUE_1ST_VERSION']==365243, 'DAYS_LAST_DUE_1ST_VERSION'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_LAST_DUE']==365243, 'DAYS_LAST_DUE'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_TERMINATION']==365243, 'DAYS_TERMINATION'] = np.nan

In [19]:
PrevLoans['NAME_CASH_LOAN_PURPOSE'].value_counts(dropna=False)

NAME_CASH_LOAN_PURPOSE
XAP                                 922661
XNA                                 677918
Repairs                              23765
Other                                15608
Urgent needs                          8412
Buying a used car                     2888
Building a house or an annex          2693
Everyday expenses                     2416
Medicine                              2174
Payments on other loans               1931
Education                             1573
Journey                               1239
Purchase of electronic equipment      1061
Buying a new car                      1012
Wedding / gift / holiday               962
Buying a home                          865
Car repairs                            797
Furniture                              749
Buying a holiday home / land           533
Business development                   426
Gasification / water supply            300
Buying a garage                        136
Hobby                                   55
Money for a third person                25
Refusal to name the goal                15
Name: count, dtype: int64

In [20]:
PrevLoans['NAME_CONTRACT_TYPE'].value_counts(dropna=False)

NAME_CONTRACT_TYPE
Cash loans         747553
Consumer loans     729151
Revolving loans    193164
XNA                   346
Name: count, dtype: int64

In [21]:
PrevLoans['NAME_YIELD_GROUP'].value_counts(dropna=False)

NAME_YIELD_GROUP
XNA           517215
middle        385532
high          353331
low_normal    322095
low_action     92041
Name: count, dtype: int64

In [22]:
PrevLoans['NAME_PORTFOLIO'].value_counts(dropna=False)

NAME_PORTFOLIO
POS      691011
Cash     461563
XNA      372230
Cards    144985
Cars        425
Name: count, dtype: int64

In [23]:
PrevLoans['FLAG_LAST_APPL_PER_CONTRACT'].value_counts(dropna=False)

FLAG_LAST_APPL_PER_CONTRACT
Y    1661739
N       8475
Name: count, dtype: int64

In [24]:
PrevLoans['NAME_SELLER_INDUSTRY'].value_counts(dropna=False)

NAME_SELLER_INDUSTRY
XNA                     855720
Consumer electronics    398265
Connectivity            276029
Furniture                57849
Construction             29781
Clothing                 23949
Industry                 19194
Auto technology           4990
Jewelry                   2709
MLM partners              1215
Tourism                    513
Name: count, dtype: int64

In [28]:
PrevLoans['CHANNEL_TYPE'].value_counts(dropna=False)

CHANNEL_TYPE
Credit and cash offices       719968
Country-wide                  494690
Stone                         212083
Regional / Local              108528
Contact center                 71297
AP+ (Cash loan)                57046
Channel of corporate sales      6150
Car dealer                       452
Name: count, dtype: int64

In [14]:
PrevLoans['NAME_CONTRACT_TYPE'].value_counts(dropna=False)

NAME_CONTRACT_TYPE
Cash loans         747553
Consumer loans     729151
Revolving loans    193164
XNA                   346
Name: count, dtype: int64

In [ ]:
temp = PrevLoans.groupby('SK_ID_CURR').agg(
    PreviousLoanCount = ('SK_ID_PREV','count'),
#   NumberofMicroFinLoans = ('NAME_CONTRACT_TYPE', lambda x: sum(x=='micro')),
    RefusedCount = ('NAME_CONTRACT_STATUS',lambda x: sum(x=='Refused')),
    ApprovedCount = ('NAME_CONTRACT_STATUS',lambda x: sum(x=='Approved')),
    PreviousLoanAvgAmount = ('AMT_CREDIT','mean'),
    PreviousLoanMaxAmount = ('AMT_CREDIT','max'),
    ApprovedLoanAvgAmount=('AMT_CREDIT', lambda x: x[PrevLoans.loc[x.index, 'NAME_CONTRACT_STATUS'] == 'Approved'].mean()),
    TermAvg = ('CNT_PAYMENT','mean'),
    TermMax = ('CNT_PAYMENT','max'),
    AvgDownpaymentAmount = ('AMT_DOWN_PAYMENT','mean'),
    MaxDownpaymentAmount = ('AMT_DOWN_PAYMENT','max'),
    AvgInterestRate = ('RATE_INTEREST_PRIMARY','mean'),
    MaxInterestRate = ('RATE_INTEREST_PRIMARY','max'),
    AvgInterestRatePrivileged = ('RATE_INTEREST_PRIVILEGED','mean'),
    MaxInterestRatePrivileged = ('RATE_INTEREST_PRIVILEGED','max'),
    NumberOfHighYieldLoans = ('NAME_YIELD_GROUP', lambda x: sum(x == 'high')),
    NumberOfCashLoans = ('NAME_CONTRACT_TYPE', lambda x: sum(x == 'Cash loans')),
    NumberOfConsumerLoans = ('NAME_CONTRACT_TYPE', lambda x: sum(x == 'Consumer loans')),
    NumberOfRevolvingLoans = ('NAME_CONTRACT_TYPE', lambda x: sum(x == 'Revolving loans')),
    NumberOfHighriskChannels = ('CHANNEL_TYPE', lambda x: sum( (x == 'AP+ (Cash loan)') | (x == 'Car dealer'))),
    TimeSinceFirstDisbursement = ('DAYS_FIRST_DRAWING','min'),
    TimeSinceLastDisbursement = ('DAYS_FIRST_DRAWING','max'),
    InsuranceRequested = ('NFLAG_INSURED_ON_APPROVAL','max'),
    NumberOfInsurance = ('NFLAG_INSURED_ON_APPROVAL','count')
)

In [8]:
PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Approved'].groupby('SK_ID_CURR').first().reset_index()

,SK_ID_CURR,SK_ID_PREV,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,100001,1369693,Consumer loans,3951.000,24835.5,23787.0,2520.0,24835.5,FRIDAY,13,...,Connectivity,8.0,high,POS mobile with interest,365243.0,-1709.0,-1499.0,-1619.0,-1612.0,0.0
1,100002,1038818,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,...,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
2,100003,1810518,Cash loans,98356.995,900000.0,1035882.0,0.0,900000.0,FRIDAY,12,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
3,100004,1564014,Consumer loans,5357.250,24282.0,20106.0,4860.0,24282.0,FRIDAY,5,...,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0
4,100005,2495675,Consumer loans,4813.200,44617.5,40153.5,4464.0,44617.5,THURSDAY,11,...,Connectivity,12.0,high,POS mobile with interest,365243.0,-706.0,-376.0,-466.0,-460.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337693,456251,2248017,Consumer loans,6605.910,40455.0,40455.0,0.0,40455.0,THURSDAY,17,...,Connectivity,8.0,high,POS mobile with interest,365243.0,-210.0,0.0,-30.0,-25.0,0.0
337694,456252,1503599,Consumer loans,10074.465,57595.5,56821.5,3456.0,57595.5,WEDNESDAY,10,...,Consumer electronics,6.0,low_normal,POS household without interest,365243.0,-2466.0,-2316.0,-2316.0,-2311.0,1.0
337695,456253,1686207,Consumer loans,5567.715,28912.5,27306.0,2893.5,28912.5,SATURDAY,12,...,Connectivity,6.0,high,POS mobile with interest,365243.0,-1866.0,-1716.0,-1716.0,-1712.0,0.0
337696,456254,2016407,Consumer loans,19065.825,223789.5,247423.5,0.0,223789.5,SATURDAY,18,...,Consumer electronics,16.0,low_normal,POS household with interest,365243.0,-247.0,203.0,365243.0,365243.0,1.0
337697,456255,1359084,Consumer loans,11314.170,82404.0,93298.5,9000.0,82404.0,SUNDAY,14,...,Connectivity,12.0,high,POS mobile with interest,365243.0,-425.0,-95.0,-215.0,-211.0,0.0

In [18]:
def get_last_approved(x, full_df):
    approved = full_df.loc[x.index, 'NAME_CONTRACT_STATUS'] == 'Approved'
    return x[approved].iloc[0] if approved.any() else np.nan

def get_last_refused(x, full_df):
    refused = full_df.loc[x.index, 'NAME_CONTRACT_STATUS'] == 'Refused'
    return x[refused].iloc[0] if refused.any() else np.nan

In [19]:
temp2 = PrevLoans.groupby('SK_ID_CURR').agg(
    DaysBetweenLoans=('DAYS_DECISION', lambda x: x.diff().mean()),
    DaysLastApproved=('DAYS_DECISION', lambda x: get_last_approved(x, PrevLoans)),
    DaysLastRefused=('DAYS_DECISION', lambda x: get_last_refused(x, PrevLoans)),
    DaysLastTermination=('DAYS_TERMINATION', lambda x: x.iloc[0]),
    LastLoanStatus=('NAME_CONTRACT_STATUS', 'last'),
    MultipleAttemptsCount=('FLAG_LAST_APPL_PER_CONTRACT', lambda x: sum(x == 'N'))
).reset_index()

In [ ]:
Loans.merge(PrevLoans, on='SK_ID_CURR', how='left')

In [3]:
CCBal = pd.read_csv('data/Internal/credit_card_balance.csv')

In [4]:
CCBal = CCBal.astype({'SK_ID_CURR': 'string', 'SK_ID_PREV': 'string'})
CCBal.dtypes

SK_ID_PREV                    string[python]
SK_ID_CURR                    string[python]
MONTHS_BALANCE                         int64
AMT_BALANCE                          float64
AMT_CREDIT_LIMIT_ACTUAL                int64
AMT_DRAWINGS_ATM_CURRENT             float64
AMT_DRAWINGS_CURRENT                 float64
AMT_DRAWINGS_OTHER_CURRENT           float64
AMT_DRAWINGS_POS_CURRENT             float64
AMT_INST_MIN_REGULARITY              float64
AMT_PAYMENT_CURRENT                  float64
AMT_PAYMENT_TOTAL_CURRENT            float64
AMT_RECEIVABLE_PRINCIPAL             float64
AMT_RECIVABLE                        float64
AMT_TOTAL_RECEIVABLE                 float64
CNT_DRAWINGS_ATM_CURRENT             float64
CNT_DRAWINGS_CURRENT                   int64
CNT_DRAWINGS_OTHER_CURRENT           float64
CNT_DRAWINGS_POS_CURRENT             float64
CNT_INSTALMENT_MATURE_CUM            float64
NAME_CONTRACT_STATUS                  object
SK_DPD                                 int64
SK_DPD_DEF                             int64
dtype: object

In [ ]:
CCBal.sort_values(by=['SK_ID_CURR', 'SK_ID_PREV', 'MONTHS_BALANCE'], ascending=[True, True, True], inplace=True)
CCBal = CCBal.reset_index(drop=True)

In [29]:
CCBal.groupby(['SK_ID_CURR','SK_ID_PREV'])[['SK_ID_CURR','SK_ID_PREV']].count()

                       SK_ID_CURR  SK_ID_PREV
SK_ID_CURR SK_ID_PREV
100006     1489396              6           6
100011     1843384             74          74
100013     2038692             96          96
100021     2594025             17          17
100023     1499902              8           8
...                           ...         ...
456244     2181926             41          41
456246     1079732              8           8
456247     1595171             95          95
456248     2743495             23          23
456250     1794451             12          12

[104307 rows x 2 columns]

In [63]:
# CCBal[(CCBal['SK_ID_CURR']=='120076')].sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'])
CCBal[(CCBal['SK_ID_CURR']=='116511')].pivot(index='MONTHS_BALANCE', columns='SK_ID_PREV', values=['NAME_CONTRACT_STATUS','AMT_BALANCE'])

               NAME_CONTRACT_STATUS         AMT_BALANCE
SK_ID_PREV                  1324396 1578039     1324396     1578039
MONTHS_BALANCE
-26                             NaN  Active         NaN         0.0
-25                             NaN  Active         NaN         0.0
-24                             NaN  Active         NaN         0.0
-23                             NaN  Active         NaN  245281.545
-22                             NaN  Active         NaN  370750.545
-21                             NaN  Active         NaN  364336.065
-20                             NaN  Active         NaN  357556.725
-19                             NaN  Active         NaN  351322.785
-18                             NaN  Active         NaN   344243.52
-17                             NaN  Active         NaN     2632.14
-16                             NaN  Active         NaN         0.0
-15                             NaN  Active         NaN         0.0
-14                             NaN  Active         NaN         0.0
-13                             NaN  Active         NaN         0.0
-12                          Signed  Active         0.0         0.0
-11                          Active  Active         0.0         0.0
-10                          Active  Active         0.0         0.0
-9                           Active  Active         0.0         0.0
-8                           Active  Active         0.0         0.0
-7                           Active  Active         0.0         0.0
-6                           Active  Active         0.0         0.0
-5                           Active  Active         0.0         0.0
-4                           Active  Active         0.0         0.0
-3                           Active  Active         0.0         0.0
-2                           Active  Active         0.0         0.0
-1                           Active  Active         0.0         0.0

In [67]:
temp = CCBal[['SK_ID_CURR','SK_ID_PREV','NAME_CONTRACT_STATUS']][
    CCBal['MONTHS_BALANCE']>=-24][
        CCBal['NAME_CONTRACT_STATUS']=='Active'
    ].drop_duplicates().sort_values(by=['SK_ID_CURR','SK_ID_PREV'])

temp2 = temp.groupby('SK_ID_CURR').agg(
    count=('SK_ID_PREV','count')
).reset_index()

temp2.query('count==1')

C:\Users\domjo\AppData\Local\Temp\ipykernel_12640\4286056043.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  temp = CCBal[['SK_ID_CURR','SK_ID_PREV','NAME_CONTRACT_STATUS']][

       SK_ID_CURR  count
0          100006      1
1          100011      1
2          100013      1
3          100021      1
4          100023      1
...           ...    ...
101245     456244      1
101246     456246      1
101247     456247      1
101248     456248      1
101249     456250      1

[100834 rows x 2 columns]

In [69]:
temp = CCBal[['SK_ID_CURR','SK_ID_PREV','NAME_CONTRACT_STATUS']][
    CCBal['MONTHS_BALANCE']==-1][
        CCBal['NAME_CONTRACT_STATUS']=='Active'
    ].drop_duplicates().sort_values(by=['SK_ID_CURR','SK_ID_PREV'])

temp2 = temp.groupby('SK_ID_CURR').agg(
    count=('SK_ID_PREV','count')
).reset_index()

temp2#.query('count==1')

C:\Users\domjo\AppData\Local\Temp\ipykernel_12640\1964592209.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  temp = CCBal[['SK_ID_CURR','SK_ID_PREV','NAME_CONTRACT_STATUS']][

      SK_ID_CURR  count
0         100006      1
1         100013      1
2         100028      1
3         100042      1
4         100043      1
...          ...    ...
56865     456225      1
56866     456233      1
56867     456237      1
56868     456242      1
56869     456250      1

[56870 rows x 2 columns]

In [40]:
# & (CCBal['SK_ID_PREV']=='1748913')
temp = CCBal[(CCBal['SK_ID_CURR']=='120076') ].sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'])[['MONTHS_BALANCE','SK_ID_PREV','AMT_BALANCE','AMT_CREDIT_LIMIT_ACTUAL','AMT_DRAWINGS_CURRENT','AMT_PAYMENT_CURRENT','AMT_PAYMENT_TOTAL_CURRENT','AMT_RECIVABLE','AMT_TOTAL_RECEIVABLE']]
temp

,MONTHS_BALANCE,SK_ID_PREV,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE
209495,-96,1334824,139260.285,225000,45000.000,53100.000,53100.000,139260.285,139260.285
209496,-95,1334824,8841.960,225000,0.000,132075.000,132075.000,8841.960,8841.960
209497,-94,1334824,139234.185,225000,135000.000,9000.000,9000.000,139234.185,139234.185
209498,-93,1334824,151297.830,225000,53100.000,48600.000,48600.000,151297.830,151297.830
209499,-92,1334824,131530.095,225000,0.000,25267.500,25267.500,131530.095,131530.095
...,...,...,...,...,...,...,...,...,...
209630,-5,2827461,2238.075,247500,87568.020,116751.555,116751.555,0.000,0.000
209631,-4,2827461,35115.570,270000,159504.705,121640.985,121640.985,33545.070,33545.070
209632,-3,2827461,44400.690,270000,113361.300,115655.670,115655.670,42830.190,42830.190
209633,-2,2827461,75788.280,270000,105290.100,101229.345,101229.345,74217.780,74217.780
209634,-1,2827461,67967.955,270000,51267.600,82477.620,82477.620,65717.955,65717.955

In [70]:
CCBal.shape

(3840312, 32)

In [71]:
temp = CCBal[CCBal['AMT_TOTAL_RECEIVABLE']<CCBal['AMT_RECEIVABLE_PRINCIPAL']]

temp[temp['AMT_RECEIVABLE_PRINCIPAL']==0].sort_values(by=['SK_ID_CURR','SK_ID_PREV','MONTHS_BALANCE'], ascending=[True, True, True])

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,SK_DPD_DEF,diff,UTILIZATION_RATIO,PAYMENT_RATIO,DRAWING_TO_PYMNT_RATIO,INT_COVERAGE_RATIO,POS_DRAWING_AMT_RATIO,ATM_DRAWING_AMT_RATIO,POS_DRAWING_CNT_RATIO,ATM_DRAWING_CNT_RATIO
38,1843384,100011,-43,804.195,180000,0.0,0.0,0.0,0.0,9000.000,...,0,-54117.450,0.446775,101.025743,0.0,-1.015328,NaN,NaN,NaN,NaN
39,1843384,100011,-42,0.000,180000,0.0,0.0,0.0,0.0,804.195,...,0,-804.195,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
40,1843384,100011,-41,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
41,1843384,100011,-40,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
42,1843384,100011,-39,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840229,1595171,456247,-49,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
3840230,1595171,456247,-48,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
3840231,1595171,456247,-47,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
3840232,1595171,456247,-46,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN
3840233,1595171,456247,-45,0.000,180000,0.0,0.0,0.0,0.0,0.000,...,0,0.000,0.000000,-0.000000,NaN,-inf,NaN,NaN,NaN,NaN

In [12]:
temp[temp['AMT_RECEIVABLE_PRINCIPAL']>0]

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
2544,1871097,100224,-62,309.780,67500,0.0,0.0,0.0,0.0,1541.070,...,57.375,57.375,0.0,0,0.0,0.0,22.0,Active,0,0
4810,1510705,100395,-67,10795.635,135000,0.0,0.0,0.0,0.0,8100.000,...,10253.970,10253.970,0.0,0,0.0,0.0,38.0,Active,0,0
4811,1510705,100395,-66,2039.580,135000,0.0,0.0,0.0,0.0,8100.000,...,1497.915,1497.915,0.0,0,0.0,0.0,39.0,Active,0,0
10047,1851029,100913,-6,178359.300,180000,0.0,178359.3,0.0,178359.3,1976.715,...,177198.705,177198.705,0.0,10,0.0,10.0,75.0,Active,0,0
33144,2287929,103054,-91,135166.275,180000,189000.0,189000.0,0.0,0.0,0.000,...,128038.275,128038.275,7.0,7,0.0,0.0,4.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3820688,1659971,454441,-57,1043.010,45000,0.0,0.0,0.0,0.0,2250.000,...,804.375,804.375,0.0,0,0.0,0.0,23.0,Active,0,0
3821793,1800723,454559,-68,1040.445,135000,0.0,0.0,0.0,0.0,8100.000,...,630.315,630.315,0.0,0,0.0,0.0,42.0,Active,0,0
3825149,2661260,454885,-48,174174.840,180000,0.0,0.0,0.0,0.0,9000.000,...,165174.840,165174.840,0.0,0,0.0,0.0,49.0,Active,0,0
3832460,1005714,455594,-62,9858.060,180000,0.0,0.0,0.0,0.0,10800.000,...,8869.185,8869.185,0.0,0,0.0,0.0,35.0,Active,0,0
3832482,1005714,455594,-40,22458.195,180000,0.0,0.0,0.0,0.0,10800.000,...,21469.320,21469.320,0.0,0,0.0,0.0,57.0,Active,0,0

In [ ]:
zero_receivable = CCBal[CCBal['AMT_TOTAL_RECEIVABLE'] == 0][['AMT_PAYMENT_CURRENT', 'AMT_DRAWINGS_CURRENT', 'AMT_BALANCE']]

zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_PAYMENT_CURRENT']>0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_12640\2076052701.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  temp = zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_PAYMENT_CURRENT']>0]

In [35]:
zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_DRAWINGS_CURRENT']==0]#[zero_receivable['AMT_PAYMENT_CURRENT']>0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_12640\675974210.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zero_receivable[zero_receivable['AMT_BALANCE']==0][zero_receivable['AMT_DRAWINGS_CURRENT']==0]#[zero_receivable['AMT_PAYMENT_CURRENT']>0]

         AMT_PAYMENT_CURRENT  AMT_DRAWINGS_CURRENT  AMT_BALANCE
0                        NaN                   0.0          0.0
1                        NaN                   0.0          0.0
2                        NaN                   0.0          0.0
3                        NaN                   0.0          0.0
4                        NaN                   0.0          0.0
...                      ...                   ...          ...
3840295                  NaN                   0.0          0.0
3840296                  NaN                   0.0          0.0
3840297                  NaN                   0.0          0.0
3840298                  NaN                   0.0          0.0
3840299                  NaN                   0.0          0.0

[2028599 rows x 3 columns]

In [172]:
CCBal[CCBal['SK_DPD'] >= 1] [CCBal['AMT_BALANCE'] >= 100]

C:\Users\domjo\AppData\Local\Temp\ipykernel_12640\848809599.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  CCBal[CCBal['SK_DPD'] >= 1] [CCBal['AMT_BALANCE'] >= 100]

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,UTILIZATION_RATIO,PAYMENT_RATIO,DRAWING_TO_PYMNT_RATIO,INT_COVERAGE_RATIO,POS_DRAWING_AMT_RATIO,ATM_DRAWING_AMT_RATIO,POS_DRAWING_CNT_RATIO,ATM_DRAWING_CNT_RATIO,DPD_past_30,DPD_UTP
107,2038692,100013,-69,105786.360,157500,0.0,0.00,0.0,0.00,7875.0,...,67.165943,0.000000,NaN,inf,NaN,NaN,NaN,NaN,0,0
264,2137382,100042,-82,90097.470,90000,0.0,14544.00,14544.0,0.00,4500.0,...,100.108300,4.598159,334.92228,74.300518,0.000000,0.000000,0.000000,0.000000,0,0
265,2137382,100042,-81,88493.715,90000,0.0,0.00,0.0,0.00,4500.0,...,98.326350,4.677593,0.00000,63.068394,NaN,NaN,NaN,NaN,0,0
493,2833536,100067,-85,47582.100,45000,2250.0,2250.00,0.0,0.00,2250.0,...,105.738000,0.000000,inf,inf,0.000000,100.000000,0.000000,100.000000,0,0
502,2833536,100067,-76,37210.410,45000,0.0,0.00,0.0,0.00,2250.0,...,82.689800,0.000000,NaN,inf,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3839867,2445843,456225,-8,192946.230,180000,10350.0,16564.95,0.0,6214.95,9000.0,...,107.192350,0.000000,inf,inf,37.518676,62.481324,66.666667,33.333333,0,0
3839896,2789041,456236,-95,40733.640,180000,18000.0,18000.00,0.0,0.00,4050.0,...,22.629800,0.000000,inf,inf,0.000000,100.000000,0.000000,100.000000,0,0
3840010,2131120,456239,-84,62258.130,135000,31500.0,31500.00,0.0,0.00,3375.0,...,46.117133,0.000000,inf,inf,0.000000,100.000000,0.000000,100.000000,0,0
3840182,1595171,456247,-96,92781.450,180000,0.0,0.00,0.0,0.00,4500.0,...,51.545250,0.000000,NaN,inf,NaN,NaN,NaN,NaN,0,0
3840192,1595171,456247,-86,190202.130,180000,0.0,0.00,0.0,0.00,9000.0,...,105.667850,0.000000,NaN,inf,NaN,NaN,NaN,NaN,0,0

In [173]:
CCBal['UTILIZATION_RATIO'] =  ( CCBal['AMT_BALANCE'] / CCBal['AMT_CREDIT_LIMIT_ACTUAL'] ) * 100  
CCBal['PAYMENT_RATIO'] = ( CCBal['AMT_PAYMENT_TOTAL_CURRENT'] / (CCBal['AMT_PAYMENT_TOTAL_CURRENT'] + CCBal['AMT_TOTAL_RECEIVABLE']) ) * 100 
CCBal['DRAWING_TO_PYMNT_RATIO'] = ( CCBal['AMT_DRAWINGS_CURRENT'] / CCBal['AMT_PAYMENT_TOTAL_CURRENT'] ) * 100   
CCBal['INT_COVERAGE_RATIO'] = ( (CCBal['AMT_TOTAL_RECEIVABLE']-CCBal['AMT_RECEIVABLE_PRINCIPAL']) / CCBal['AMT_PAYMENT_TOTAL_CURRENT'] ) * 100   
CCBal['POS_DRAWING_AMT_RATIO'] = ( CCBal['AMT_DRAWINGS_POS_CURRENT'] / CCBal['AMT_DRAWINGS_CURRENT'] ) * 100  
CCBal['ATM_DRAWING_AMT_RATIO'] = ( CCBal['AMT_DRAWINGS_ATM_CURRENT'] / CCBal['AMT_DRAWINGS_CURRENT'] ) * 100  

CCBal['POS_DRAWING_CNT_RATIO'] = ( CCBal['CNT_DRAWINGS_POS_CURRENT'] / CCBal['CNT_DRAWINGS_CURRENT'] ) * 100  
CCBal['ATM_DRAWING_CNT_RATIO'] = ( CCBal['CNT_DRAWINGS_ATM_CURRENT'] / CCBal['CNT_DRAWINGS_CURRENT'] ) * 100  

CCBal['DPD'] = ( CCBal['SK_DPD'] >= 7 ) * 1
CCBal['DPD_UTP'] = ( (CCBal['SK_DPD'] >= 1) & (CCBal['AMT_BALANCE'] >= 100) ) * 1

In [153]:
x = CCBal[CCBal['SK_ID_CURR']=='456247']['MONTHS_BALANCE']

In [155]:
months_bal = CCBal.loc[x.index] [CCBal.loc[x.index,'SK_DPD']>=1]
months_bal

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,UTILIZATION_RATIO,PAYMENT_RATIO,DRAWING_TO_PYMNT_RATIO,INT_COVERAGE_RATIO,POS_DRAWING_AMT_RATIO,ATM_DRAWING_AMT_RATIO,POS_DRAWING_CNT_RATIO,ATM_DRAWING_CNT_RATIO,DPD_past_30,DPD_UTP
3840182,1595171,456247,-96,92781.45,180000,0.0,0.0,0.0,0.0,4500.00,...,51.54525,0.0,NaN,inf,NaN,NaN,NaN,NaN,0,0
3840192,1595171,456247,-86,190202.13,180000,0.0,0.0,0.0,0.0,9000.00,...,105.66785,0.0,NaN,inf,NaN,NaN,NaN,NaN,0,0
3840201,1595171,456247,-77,43.83,180000,0.0,0.0,0.0,0.0,43.83,...,0.02435,0.0,NaN,inf,NaN,NaN,NaN,NaN,0,0

In [171]:
CCBal[CCBal['SK_ID_CURR']=='100086']#[['SK_ID_CURR','MONTHS_BALANCE','SK_DPD','SK_DPD_DEF']]

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,UTILIZATION_RATIO,PAYMENT_RATIO,DRAWING_TO_PYMNT_RATIO,INT_COVERAGE_RATIO,POS_DRAWING_AMT_RATIO,ATM_DRAWING_AMT_RATIO,POS_DRAWING_CNT_RATIO,ATM_DRAWING_CNT_RATIO,DPD_past_30,DPD_UTP
704,1856124,100086,-84,0.000,112500,NaN,0.0,NaN,NaN,NaN,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
705,1856124,100086,-83,0.000,112500,NaN,0.0,NaN,NaN,NaN,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
706,1856124,100086,-82,0.000,112500,NaN,0.0,NaN,NaN,NaN,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
707,1856124,100086,-81,115697.925,112500,112500.0,112500.0,0.0,0.0,NaN,...,102.84260,0.000000,inf,inf,0.0,100.0,0.0,100.0,0,0
708,1856124,100086,-80,114419.610,112500,0.0,0.0,0.0,0.0,5625.0,...,101.70632,4.685758,0.0,77.2744,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,1856124,100086,-5,0.000,45000,0.0,0.0,0.0,0.0,0.0,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
784,1856124,100086,-4,0.000,45000,0.0,0.0,0.0,0.0,0.0,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
785,1856124,100086,-3,0.000,45000,0.0,0.0,0.0,0.0,0.0,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
786,1856124,100086,-2,0.000,45000,0.0,0.0,0.0,0.0,0.0,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
787,1856124,100086,-1,0.000,45000,0.0,0.0,0.0,0.0,0.0,...,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

In [ ]:
def get_days_to_first_dpd(x):
    
    months_bal = CCBal.loc[x.index][CCBal.loc[x.index,'SK_DPD']>=7]
    if months_bal.shape[0] > 0:
        return months_bal['MONTHS_BALANCE'].min() * -30
    else:
        return np.nan

In [176]:
temp = CCBal.groupby('SK_ID_CURR').agg(
    CreditCard_Max_Duration=('MONTHS_BALANCE','min'),
    CreditCard_Count=('SK_ID_PREV','nunique'),
    CreditCard_Avg_Limit=('AMT_CREDIT_LIMIT_ACTUAL','mean'),
    CreditCard_Avg_Balance=('AMT_BALANCE','mean'),
    CreditCard_Avg_Payment=('AMT_PAYMENT_TOTAL_CURRENT','mean'),
    CreditCard_Max_Utilization_Rate=('UTILIZATION_RATIO','mean'),
    CreditCard_Avg_Payment_Rate=('PAYMENT_RATIO','mean'),
    CreditCard_Avg_DrawingToPayment_Rate=('DRAWING_TO_PYMNT_RATIO','mean'),
    CreditCard_Avg_IntCoverage_Rate=('INT_COVERAGE_RATIO','mean'),
    CreditCard_Avg_POSAmt_Rate=('POS_DRAWING_AMT_RATIO','mean'),
    CreditCard_Avg_ATMAmt_Rate=('ATM_DRAWING_AMT_RATIO','mean'),
    CreditCard_Avg_POSCount_Rate=('POS_DRAWING_CNT_RATIO','mean'),
    CreditCard_Avg_ATMCount_Rate=('ATM_DRAWING_CNT_RATIO','mean'),
    CreditCard_Avg_RepaymentCount_Rate=('CNT_INSTALMENT_MATURE_CUM', lambda x: x[x > 0].count()/x.count()),
    CreditCard_DPD=('DPD','max'),
    CreditCard_DPDUTP=('DPD_UTP','max'),
    CreditCard_DaysToDPD=('MONTHS_BALANCE', lambda x: get_days_to_first_dpd(x)),
    CreditCard_DaysinDPD_Rate=('SK_DPD', lambda x: x[x >= 1].count()/x.count() )
).reset_index()

In [3]:
Payments = pd.read_csv('data/Internal/installments_payments.csv')

In [4]:
Payments.head()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585

In [8]:
POSBal = pd.read_csv('data/Internal/POS_CASH_balance.csv')

In [11]:
POSBal.head(10)

NameError: name 'POSBal' is not defined

In [3]:
Bureau = pd.read_csv('data/External/bureau.csv')

In [5]:
Bureau = Bureau.astype({'SK_ID_CURR': 'string', 'SK_ID_BUREAU': 'string'})

In [6]:
Bureau.dtypes

SK_ID_CURR                string[python]
SK_ID_BUREAU              string[python]
CREDIT_ACTIVE                     object
CREDIT_CURRENCY                   object
DAYS_CREDIT                        int64
CREDIT_DAY_OVERDUE                 int64
DAYS_CREDIT_ENDDATE              float64
DAYS_ENDDATE_FACT                float64
AMT_CREDIT_MAX_OVERDUE           float64
CNT_CREDIT_PROLONG                 int64
AMT_CREDIT_SUM                   float64
AMT_CREDIT_SUM_DEBT              float64
AMT_CREDIT_SUM_LIMIT             float64
AMT_CREDIT_SUM_OVERDUE           float64
CREDIT_TYPE                       object
DAYS_CREDIT_UPDATE                 int64
AMT_ANNUITY                      float64
dtype: object

In [7]:
Bureau.shape

(1716428, 17)

In [8]:
# ...existing code...
# Find groups with more than one row (i.e., duplicates)
dupes = (
    Bureau.groupby(['SK_ID_CURR', 'SK_ID_BUREAU'])
    .size()
    .reset_index(name='count')
)
dupes = dupes[dupes['count'] > 1]
dupes
# ...existing code...

Empty DataFrame
Columns: [SK_ID_CURR, SK_ID_BUREAU, count]
Index: []

In [31]:
df = Bureau[['SK_ID_BUREAU','DAYS_CREDIT','CREDIT_ACTIVE','CREDIT_TYPE','AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_OVERDUE']].head(10000)

Credit card limit (mostly relevant for credit cards, missing or 0 for other types).

In [19]:
Bureau[Bureau['AMT_CREDIT_SUM_LIMIT']>0]['CREDIT_TYPE'].value_counts(dropna=False)

CREDIT_TYPE
Credit card        74119
Consumer credit       26
Car loan              10
Name: count, dtype: int64

In [ ]:
Bureau.sample(20)[['SK_ID_BUREAU','CREDIT_ACTIVE','CREDIT_TYPE','AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT']]

In [48]:
Bureau['Duration'] = Bureau['DAYS_CREDIT_ENDDATE'] - Bureau['DAYS_CREDIT'] 
#Bureau['UtilizationRate'] = Bureau['AMT_CREDIT_SUM_DEBT'] / Bureau['AMT_CREDIT_SUM'] if x['AMT_CREDIT_SUM'] > 0 else np.nan

In [ ]:
Bureau.isnull().sum()

SK_ID_CURR                      0
SK_ID_BUREAU                    0
CREDIT_ACTIVE                   0
CREDIT_CURRENCY                 0
DAYS_CREDIT                     0
CREDIT_DAY_OVERDUE              0
DAYS_CREDIT_ENDDATE        105553
DAYS_ENDDATE_FACT          633653
AMT_CREDIT_MAX_OVERDUE    1124488
CNT_CREDIT_PROLONG              0
AMT_CREDIT_SUM                 13
AMT_CREDIT_SUM_DEBT        257669
AMT_CREDIT_SUM_LIMIT       591780
AMT_CREDIT_SUM_OVERDUE          0
CREDIT_TYPE                     0
DAYS_CREDIT_UPDATE              0
AMT_ANNUITY               1226791
dtype: int64

In [39]:
Bureau.sample(20)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
1427076,347766,6741337,Closed,currency 1,-929,0,NaN,-801.0,NaN,0,22500.0,0.0,NaN,0.0,Consumer credit,-801,NaN
570180,428068,5681733,Closed,currency 1,-19,0,-3.0,-6.0,NaN,0,63000.0,0.0,0.0,0.0,Consumer credit,-2,NaN
427329,158475,6830990,Closed,currency 1,-1121,0,-938.0,-938.0,NaN,0,88006.5,0.0,NaN,0.0,Consumer credit,-932,NaN
1002400,414444,5454745,Closed,currency 1,-308,0,-202.0,-202.0,NaN,0,55732.5,0.0,NaN,0.0,Consumer credit,-137,38497.5
458804,120961,5040844,Closed,currency 1,-2250,0,-425.0,-1314.0,NaN,0,1350000.0,0.0,0.0,0.0,Consumer credit,-677,NaN
1227525,281935,5188733,Closed,currency 1,-78,0,-63.0,-65.0,NaN,0,22500.0,0.0,NaN,0.0,Microloan,-35,NaN
564437,176656,5683899,Closed,currency 1,-2301,0,-1814.0,-1831.0,NaN,0,164205.0,0.0,NaN,0.0,Consumer credit,-1811,0.0
690721,287704,5317517,Closed,currency 1,-2029,0,-1299.0,-1483.0,36712.845,0,315000.0,0.0,0.0,0.0,Consumer credit,-1483,NaN
37593,253642,5809370,Closed,currency 1,-396,0,-92.0,-92.0,0.000,0,318573.0,0.0,0.0,0.0,Consumer credit,-90,NaN
668244,416588,5021435,Closed,currency 1,-1531,0,-1225.0,-1225.0,0.000,0,23279.4,NaN,NaN,0.0,Consumer credit,-260,0.0
704065,198101,5491208,Closed,currency 1,-2467,0,-2255.0,-2281.0,NaN,0,32511.6,0.0,NaN,0.0,Consumer credit,-886,NaN
899838,292319,5467616,Active,currency 1,-244,0,1582.0,NaN,NaN,0,805500.0,756882.0,0.0,0.0,Consumer credit,-4,22477.5
1480764,455791,5354221,Closed,currency 1,-1754,0,-1449.0,-1432.0,NaN,0,136309.5,0.0,0.0,0.0,Consumer credit,-939,42862.5
771166,317563,5379316,Active,currency 1,-196,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-10,NaN
1196462,438122,5300056,Closed,currency 1,-680,0,-379.0,-379.0,NaN,0,104895.0,0.0,NaN,0.0,Consumer credit,-356,NaN
230906,225226,5845800,Closed,currency 1,-652,0,-287.0,-316.0,0.000,0,78529.5,0.0,0.0,0.0,Consumer credit,-316,NaN
25725,124689,5201320,Active,currency 1,-109,0,74.0,NaN,0.000,0,15255.0,7983.0,0.0,0.0,Consumer credit,-15,NaN
638876,133366,6229730,Active,currency 1,-1055,0,-18.0,NaN,NaN,0,0.0,0.0,0.0,0.0,Credit card,-25,NaN
369201,246997,5531949,Closed,currency 1,-1098,0,729.0,-580.0,NaN,0,3667500.0,0.0,0.0,0.0,Consumer credit,-545,NaN
390754,129986,5188570,Sold,currency 1,-1959,0,-1593.0,NaN,NaN,0,50557.5,NaN,NaN,0.0,Credit card,-1898,NaN

In [49]:
def get_utilization_rate(x, fulldf):
    y = fulldf.loc[x.index]
    active = y[y['CREDIT_ACTIVE'] == 'Active']
    return np.mean(np.where(
                                y['AMT_CREDIT_SUM'] > 0,
                                y['AMT_CREDIT_SUM_DEBT'] / y['AMT_CREDIT_SUM'],
                                np.nan
                            ) )

In [50]:
Bureau.groupby('SK_ID_CURR').agg(

    BureauTotalCreditCount=('SK_ID_BUREAU', 'count'),
    BureauTotalActiveCreditCount=('SK_ID_BUREAU', lambda x: sum(Bureau.loc[x.index, 'CREDIT_ACTIVE'] == 'Active')),
    BureauPastBadCreditCount=('SK_ID_BUREAU', lambda x: sum(Bureau.loc[x.index, 'CREDIT_ACTIVE'] == 'Bad debt')),
    BureauPastSoldCreditCount=('SK_ID_BUREAU', lambda x: sum(Bureau.loc[x.index, 'CREDIT_ACTIVE'] == 'Sold')),

    BureauDaysToLastCredit=('DAYS_CREDIT', 'max'),
    BureauAvgDaysToCredit=('DAYS_CREDIT', lambda x: x.sort_values(ascending=True).diff().mean() ),
    BureauAvgDuration=('Duration', 'mean'),
    BureauMaxDaysCreditEnd=('DAYS_CREDIT_ENDDATE', 'max'),

    BureauIsPastOverdueFlag=('CREDIT_DAY_OVERDUE', lambda x: (x > 0).any() * 1),
    BureauActiveUtilizationRatio=('SK_ID_BUREAU', lambda x: get_utilization_rate(x, Bureau)),    

    BureauMaxCreditOverdueAmount=('AMT_CREDIT_MAX_OVERDUE', 'max'),
    BureauAvgCreditAmount=('AMT_CREDIT_SUM', 'mean')

)

,BureauTotalCreditCount,BureauTotalActiveCreditCount,BureauPastBadCreditCount,BureauPastSoldCreditCount,BureauDaysToLastCredit,BureauAvgDaysToCredit,BureauAvgDuration,BureauMaxDaysCreditEnd,BureauIsPastOverdueFlag,BureauActiveUtilizationRatio,BureauMaxCreditOverdueAmount,BureauAvgCreditAmount
SK_ID_CURR,,,,,,,,,,,,
100001,7,3,0,0,-49,253.833333,817.428571,1778.0,0,0.282518,NaN,2.076236e+05
100002,8,2,0,0,-103,190.571429,719.833333,780.0,0,NaN,5043.645,1.081319e+05
100003,4,1,0,0,-606,660.000000,856.250000,1216.0,0,0.000000,0.000,2.543501e+05
100004,2,0,0,0,-408,918.000000,378.500000,-382.0,0,0.000000,0.000,9.451890e+04
100005,3,2,0,0,-62,155.500000,630.000000,1324.0,0,0.601256,0.000,2.190420e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
456249,13,2,0,0,-483,185.833333,433.666667,1363.0,0,NaN,18945.000,2.841430e+05
456250,3,2,0,0,-760,121.000000,2150.333333,2340.0,0,0.575079,0.000,1.028820e+06
456253,4,2,0,0,-713,68.666667,1148.000000,1113.0,0,0.299308,NaN,9.900000e+05
456254,1,0,0,0,-1104,NaN,245.000000,-859.0,0,0.000000,NaN,4.500000e+04
456255,11,5,0,0,-363,197.400000,4320.727273,27320.0,0,NaN,25578.000,3.456290e+05

In [37]:
Bureau['DAYS_CREDIT'].max()

0

In [51]:
Bureau[Bureau['SK_ID_CURR'] == '100011']

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,Duration
420732,100011,5741082,Closed,currency 1,-2508,0,-2173.0,-2197.0,10147.23,0,90744.3,0.0,0.0,0.0,Consumer credit,-2172,NaN,335.0
420733,100011,5741083,Closed,currency 1,-1960,0,-860.0,-1618.0,0.00,0,54000.0,0.0,0.0,0.0,Credit card,-1618,NaN,1100.0
420734,100011,5741084,Closed,currency 1,-1309,0,-1070.0,-1070.0,NaN,0,145242.0,0.0,0.0,0.0,Consumer credit,-1064,NaN,239.0
420735,100011,5741085,Closed,currency 1,-1315,0,-1070.0,-968.0,NaN,0,145242.0,NaN,NaN,0.0,Consumer credit,-965,NaN,245.0

In [16]:
Bureau.groupby('SK_ID_CURR').apply(
    lambda x: x.sort_values('DAYS_CREDIT',ascending=False).head(1)
).reset_index(drop=True)

MemoryError:

In [10]:
Bureau['CREDIT_ACTIVE'].value_counts(dropna=False)

CREDIT_ACTIVE
Closed      1079273
Active       630607
Sold           6527
Bad debt         21
Name: count, dtype: int64

In [11]:
Bureau['CREDIT_CURRENCY'].value_counts(dropna=False)

CREDIT_CURRENCY
currency 1    1715020
currency 2       1224
currency 3        174
currency 4         10
Name: count, dtype: int64

In [6]:
BureauBal = pd.read_csv('data/External/bureau_balance.csv')

In [ ]:
BureauBal.head()

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C