In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.getcwd()
os.chdir('a:\\Dominic\\My Projects\\Home Credit\\')

In [3]:
PrevLoans = pd.read_csv('data/Internal/previous_application.csv')

In [4]:
PrevLoans.shape

(1670214, 37)

Convert data type and order by `DAYS_DECISION`.

In [5]:
PrevLoans = PrevLoans.astype({'SK_ID_CURR': 'string', 'SK_ID_PREV': 'string'})
PrevLoans.dtypes

SK_ID_PREV                     string[python]
SK_ID_CURR                     string[python]
NAME_CONTRACT_TYPE                     object
AMT_ANNUITY                           float64
AMT_APPLICATION                       float64
AMT_CREDIT                            float64
AMT_DOWN_PAYMENT                      float64
AMT_GOODS_PRICE                       float64
WEEKDAY_APPR_PROCESS_START             object
HOUR_APPR_PROCESS_START                 int64
FLAG_LAST_APPL_PER_CONTRACT            object
NFLAG_LAST_APPL_IN_DAY                  int64
RATE_DOWN_PAYMENT                     float64
RATE_INTEREST_PRIMARY                 float64
RATE_INTEREST_PRIVILEGED              float64
NAME_CASH_LOAN_PURPOSE                 object
NAME_CONTRACT_STATUS                   object
DAYS_DECISION                           int64
NAME_PAYMENT_TYPE                      object
CODE_REJECT_REASON                     object
NAME_TYPE_SUITE                        object
NAME_CLIENT_TYPE                       object
NAME_GOODS_CATEGORY                    object
NAME_PORTFOLIO                         object
NAME_PRODUCT_TYPE                      object
CHANNEL_TYPE                           object
SELLERPLACE_AREA                        int64
NAME_SELLER_INDUSTRY                   object
CNT_PAYMENT                           float64
NAME_YIELD_GROUP                       object
PRODUCT_COMBINATION                    object
DAYS_FIRST_DRAWING                    float64
DAYS_FIRST_DUE                        float64
DAYS_LAST_DUE_1ST_VERSION             float64
DAYS_LAST_DUE                         float64
DAYS_TERMINATION                      float64
NFLAG_INSURED_ON_APPROVAL             float64
dtype: object

In [6]:
# Sort by SK_ID_CURR and DAYS_DECISION
PrevLoans.sort_values(by=['SK_ID_CURR', 'DAYS_DECISION'], ascending=[True, False], inplace=True)

In [7]:
PrevLoans.head(25)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
201668,1369693,100001,Consumer loans,3951.000,24835.50,23787.0,2520.00,24835.50,FRIDAY,13,...,Connectivity,8.0,high,POS mobile with interest,365243.0,-1709.0,-1499.0,-1619.0,-1612.0,0.0
892077,1038818,100002,Consumer loans,9251.775,179055.00,179055.0,0.00,179055.00,SATURDAY,9,...,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
575941,1810518,100003,Cash loans,98356.995,900000.00,1035882.0,NaN,900000.00,FRIDAY,12,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
1021650,2636178,100003,Consumer loans,64567.665,337500.00,348637.5,0.00,337500.00,SUNDAY,17,...,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
1223745,2396755,100003,Consumer loans,6737.310,68809.50,68053.5,6885.00,68809.50,SATURDAY,15,...,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
935548,1564014,100004,Consumer loans,5357.250,24282.00,20106.0,4860.00,24282.00,FRIDAY,5,...,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0
1259112,1857999,100005,Cash loans,NaN,0.00,0.0,NaN,NaN,FRIDAY,10,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1378978,2495675,100005,Consumer loans,4813.200,44617.50,40153.5,4464.00,44617.50,THURSDAY,11,...,Connectivity,12.0,high,POS mobile with interest,365243.0,-706.0,-376.0,-466.0,-460.0,0.0
98162,2078043,100006,Cash loans,24246.000,675000.00,675000.0,NaN,675000.00,THURSDAY,15,...,XNA,48.0,low_normal,Cash X-Sell: low,365243.0,-151.0,1259.0,-151.0,-143.0,0.0
617859,2827850,100006,Revolving loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
900957,1489396,100006,Revolving loans,13500.000,270000.00,270000.0,NaN,270000.00,THURSDAY,15,...,XNA,0.0,XNA,Card X-Sell,365243.0,365243.0,365243.0,365243.0,365243.0,0.0
1232752,1243599,100006,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1595430,2545789,100006,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1607443,1697039,100006,Cash loans,32696.100,688500.00,906615.0,NaN,688500.00,THURSDAY,15,...,XNA,48.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
830967,2190416,100006,Consumer loans,29027.520,334917.00,267930.0,66987.00,334917.00,SUNDAY,15,...,Consumer electronics,12.0,high,POS household with interest,365243.0,-281.0,49.0,365243.0,365243.0,0.0
1131133,1020698,100006,Cash loans,39954.510,454500.00,481495.5,NaN,454500.00,SATURDAY,12,...,XNA,18.0,high,Cash X-Sell: high,NaN,NaN,NaN,NaN,NaN,NaN
1333657,2299329,100006,Consumer loans,2482.920,26912.34,24219.0,2693.34,26912.34,TUESDAY,15,...,Construction,12.0,middle,POS industry with interest,365243.0,-545.0,-215.0,-425.0,-416.0,0.0
693308,1692033,100007,Cash loans,16037.640,247500.00,274288.5,NaN,247500.00,MONDAY,11,...,XNA,24.0,middle,Cash X-Sell: middle,365243.0,-344.0,346.0,365243.0,365243.0,1.0
13392,2001242,100007,Cash loans,16509.600,180000.00,180000.0,NaN,180000.00,SUNDAY,14,...,Consumer electronics,18.0,high,Cash Street: high,365243.0,-834.0,-324.0,-354.0,-347.0,0.0
87569,2730157,100007,Cash loans,13010.985,225000.00,284400.0,NaN,225000.00,FRIDAY,13,...,XNA,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
1483068,1940724,100007,Cash loans,22678.785,202500.00,215865.0,NaN,202500.00,THURSDAY,8,...,Consumer electronics,12.0,middle,Cash X-Sell: middle,365243.0,-1076.0,-746.0,-746.0,-739.0,1.0
1260339,2462742,100007,Consumer loans,3601.530,31005.00,30663.0,3105.00,31005.00,SUNDAY,15,...,Connectivity,12.0,high,POS mobile with interest,365243.0,-1736.0,-1406.0,-1406.0,-1397.0,0.0
1061094,2119973,100007,Consumer loans,1834.290,17176.50,14616.0,3676.50,17176.50,SATURDAY,13,...,Consumer electronics,10.0,high,POS household with interest,365243.0,-2326.0,-2056.0,-2056.0,-2041.0,1.0
600145,1757431,100008,Cash loans,NaN,0.00,0.0,NaN,NaN,FRIDAY,18,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
320227,2218188,100008,Consumer loans,17885.835,162598.50,162598.5,0.00,162598.50,THURSDAY,10,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-339.0,-69.0,-69.0,-66.0,0.0

In [8]:
PrevLoans['NAME_PORTFOLIO'].value_counts(dropna=False)

NAME_PORTFOLIO
POS      691011
Cash     461563
XNA      372230
Cards    144985
Cars        425
Name: count, dtype: int64

In [9]:
PrevLoans['NAME_CONTRACT_TYPE'].value_counts(dropna=False)

NAME_CONTRACT_TYPE
Cash loans         747553
Consumer loans     729151
Revolving loans    193164
XNA                   346
Name: count, dtype: int64

In [10]:
PrevLoans.groupby(['NAME_PORTFOLIO','NAME_CONTRACT_TYPE']).size().sort_values(ascending=False).head(25)

NAME_PORTFOLIO  NAME_CONTRACT_TYPE
POS             Consumer loans        691011
Cash            Cash loans            461563
XNA             Cash loans            285990
Cards           Revolving loans       144985
XNA             Revolving loans        48179
                Consumer loans         37715
Cars            Consumer loans           425
XNA             XNA                      346
dtype: int64

In [11]:
PrevLoans['NAME_CONTRACT_STATUS'].value_counts(dropna=False)

NAME_CONTRACT_STATUS
Approved        1036781
Canceled         316319
Refused          290678
Unused offer      26436
Name: count, dtype: int64

Approved but `AMT_CREDIT` = 0.

Which means,it was later cancelled. Hence to be removed from data

In [12]:
PrevLoans[(PrevLoans['AMT_CREDIT']==0) & (PrevLoans['NAME_CONTRACT_STATUS']=='Approved')]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
692071,2313600,101136,Revolving loans,0.0,0.0,0.0,NaN,0.0,WEDNESDAY,17,...,Consumer electronics,0.0,XNA,Card Street,-193.0,365243.0,365243.0,365243.0,365243.0,0.0
1160277,2575385,101196,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,13,...,Consumer electronics,0.0,XNA,Card Street,-90.0,365243.0,365243.0,365243.0,365243.0,0.0
1056809,1081051,101622,Revolving loans,0.0,0.0,0.0,NaN,0.0,MONDAY,12,...,Consumer electronics,0.0,XNA,Card Street,-241.0,-201.0,365243.0,-140.0,-101.0,0.0
1105923,1666991,101669,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,19,...,Connectivity,0.0,XNA,Card Street,-338.0,365243.0,365243.0,365243.0,365243.0,0.0
588884,2824785,101734,Revolving loans,0.0,0.0,0.0,NaN,0.0,SATURDAY,15,...,Consumer electronics,0.0,XNA,Card Street,-332.0,365243.0,365243.0,365243.0,365243.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548767,2780308,455312,Revolving loans,0.0,0.0,0.0,NaN,0.0,THURSDAY,11,...,Connectivity,0.0,XNA,Card Street,-279.0,365243.0,365243.0,365243.0,365243.0,0.0
13335,2272045,455494,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,9,...,Consumer electronics,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0
1012354,2697654,455539,Revolving loans,0.0,0.0,0.0,NaN,0.0,MONDAY,11,...,Consumer electronics,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0
1300855,1053330,455720,Revolving loans,0.0,0.0,0.0,NaN,0.0,SATURDAY,8,...,Connectivity,0.0,XNA,Card Street,-240.0,365243.0,365243.0,365243.0,365243.0,0.0
779847,1209934,456013,Revolving loans,0.0,0.0,0.0,NaN,0.0,TUESDAY,13,...,Consumer electronics,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0

In [13]:
PrevLoans[(PrevLoans['AMT_CREDIT'].isna()) & (PrevLoans['NAME_CONTRACT_STATUS']=='Approved')]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1127152,2204450,438387,Revolving loans,0.0,0.0,NaN,NaN,NaN,FRIDAY,10,...,Connectivity,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN

`Refused` but `AMT_CREDIT` > 0.

To be handled seperately.
- Avg AMT_GOODS_PRICE 
- Avg AMT_CREDIT
- Last refused
- Number refused in last 120 days,240 days

In [14]:
# records where NAME_CONTRACT_STATUS is 'Refused' and AMT_CREDIT > 0
PrevLoans[((PrevLoans['NAME_CONTRACT_STATUS'] == 'Refused') & (PrevLoans['AMT_CREDIT'] > 0))]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1607443,1697039,100006,Cash loans,32696.100,688500.000,906615.000,NaN,688500.000,THURSDAY,15,...,XNA,48.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
35014,2531618,100027,Cash loans,22556.475,225000.000,239850.000,NaN,225000.000,SATURDAY,14,...,XNA,12.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
780467,1625550,100030,Consumer loans,NaN,21969.225,21969.225,0.0,21969.225,SATURDAY,13,...,Connectivity,NaN,XNA,POS mobile with interest,NaN,NaN,NaN,NaN,NaN,NaN
1312908,1354305,100030,Consumer loans,6014.835,33561.000,27954.000,6714.0,33561.000,SUNDAY,15,...,Connectivity,5.0,low_normal,POS mobile without interest,NaN,NaN,NaN,NaN,NaN,NaN
330351,2197792,100030,Consumer loans,NaN,33250.500,33250.500,0.0,33250.500,WEDNESDAY,12,...,Connectivity,NaN,XNA,POS mobile with interest,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749319,2390857,456247,Consumer loans,NaN,52510.500,52510.500,0.0,52510.500,SUNDAY,13,...,Connectivity,NaN,XNA,POS mobile with interest,NaN,NaN,NaN,NaN,NaN,NaN
234061,2669123,456249,Consumer loans,11497.500,114210.000,125518.500,0.0,114210.000,WEDNESDAY,11,...,Consumer electronics,12.0,low_action,POS household without interest,NaN,NaN,NaN,NaN,NaN,NaN
1440475,2626069,456250,Cash loans,19151.100,450000.000,533160.000,NaN,450000.000,THURSDAY,7,...,XNA,48.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
814647,1296007,456255,Cash loans,30737.655,765000.000,1067940.000,NaN,765000.000,FRIDAY,14,...,XNA,60.0,low_normal,Cash Street: low,NaN,NaN,NaN,NaN,NaN,NaN
729432,1708056,456255,Revolving loans,2250.000,45000.000,45000.000,NaN,45000.000,SUNDAY,14,...,Connectivity,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN

`Canceled` but `AMT_CREDIT` > 0.

Required as amount is approved although cancelled by client.

In [15]:
PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']>0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_23148\1024469317.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']>0]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1064064,2237361,100038,Cash loans,24463.710,454500.0,508495.5,NaN,454500.0,TUESDAY,7,...,XNA,36.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
888028,1227828,100062,Cash loans,26316.000,900000.0,900000.0,NaN,900000.0,TUESDAY,19,...,XNA,60.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
1132970,1475898,100072,Cash loans,76091.760,1467000.0,1467000.0,NaN,1467000.0,THURSDAY,11,...,XNA,24.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
440306,1712955,100086,Cash loans,21775.500,675000.0,675000.0,NaN,675000.0,SATURDAY,14,...,XNA,60.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
1613283,2487942,100189,Cash loans,25475.625,562500.0,562500.0,NaN,562500.0,MONDAY,17,...,Furniture,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199606,1357202,456063,Cash loans,48334.950,810000.0,865597.5,NaN,810000.0,MONDAY,8,...,XNA,24.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
1363215,2619866,456079,Cash loans,50197.770,1354500.0,1354500.0,NaN,1354500.0,SATURDAY,15,...,XNA,36.0,low_action,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
469973,1971829,456088,Cash loans,30570.750,675000.0,675000.0,NaN,675000.0,FRIDAY,12,...,XNA,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
1642212,2626164,456186,Cash loans,27193.500,450000.0,450000.0,NaN,450000.0,WEDNESDAY,12,...,XNA,36.0,high,Cash X-Sell: high,NaN,NaN,NaN,NaN,NaN,NaN
565083,2355581,456235,Cash loans,12377.610,265500.0,265500.0,NaN,265500.0,THURSDAY,11,...,XNA,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN

`Canceled` and `AMT_CREDIT` = 0

In [16]:
PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']==0]

C:\Users\domjo\AppData\Local\Temp\ipykernel_23148\3749386403.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  PrevLoans[PrevLoans['NAME_CONTRACT_STATUS']=='Canceled'][PrevLoans['AMT_CREDIT']==0]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1259112,1857999,100005,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,10,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
617859,2827850,100006,Revolving loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
1232752,1243599,100006,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1595430,2545789,100006,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
600145,1757431,100008,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,18,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882795,1842078,456244,Cash loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,12,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1472002,1842431,456244,Cash loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,12,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1094543,1482581,456250,Revolving loans,NaN,0.0,0.0,NaN,NaN,MONDAY,11,...,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
1345759,2624169,456250,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,8,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
553648,1511244,456250,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,7,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
PrevLoans['NAME_CASH_LOAN_PURPOSE'].value_counts(dropna=False)

NAME_CASH_LOAN_PURPOSE
XAP                                 922661
XNA                                 677918
Repairs                              23765
Other                                15608
Urgent needs                          8412
Buying a used car                     2888
Building a house or an annex          2693
Everyday expenses                     2416
Medicine                              2174
Payments on other loans               1931
Education                             1573
Journey                               1239
Purchase of electronic equipment      1061
Buying a new car                      1012
Wedding / gift / holiday               962
Buying a home                          865
Car repairs                            797
Furniture                              749
Buying a holiday home / land           533
Business development                   426
Gasification / water supply            300
Buying a garage                        136
Hobby                                   55
Money for a third person                25
Refusal to name the goal                15
Name: count, dtype: int64

In [18]:
PrevLoans['NAME_YIELD_GROUP'].value_counts(dropna=False)

NAME_YIELD_GROUP
XNA           517215
middle        385532
high          353331
low_normal    322095
low_action     92041
Name: count, dtype: int64

In [19]:
PrevLoans['FLAG_LAST_APPL_PER_CONTRACT'].value_counts(dropna=False)

FLAG_LAST_APPL_PER_CONTRACT
Y    1661739
N       8475
Name: count, dtype: int64

In [20]:
PrevLoans['NAME_SELLER_INDUSTRY'].value_counts(dropna=False)

NAME_SELLER_INDUSTRY
XNA                     855720
Consumer electronics    398265
Connectivity            276029
Furniture                57849
Construction             29781
Clothing                 23949
Industry                 19194
Auto technology           4990
Jewelry                   2709
MLM partners              1215
Tourism                    513
Name: count, dtype: int64

Refers to the channel or method through which a previous loan was applied for or originated. This column categorizes how borrowers interacted with the lender when obtaining their past loans.

In [21]:
PrevLoans['CHANNEL_TYPE'].value_counts(dropna=False)

CHANNEL_TYPE
Credit and cash offices       719968
Country-wide                  494690
Stone                         212083
Regional / Local              108528
Contact center                 71297
AP+ (Cash loan)                57046
Channel of corporate sales      6150
Car dealer                       452
Name: count, dtype: int64

In [22]:
PrevLoans['NAME_YIELD_GROUP'].value_counts(dropna=False)

NAME_YIELD_GROUP
XNA           517215
middle        385532
high          353331
low_normal    322095
low_action     92041
Name: count, dtype: int64

Replace `365243` in somecolumns with `nan` as they are invalid entries.

In [23]:
PrevLoans[(PrevLoans==365243).any(axis=1)]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
201668,1369693,100001,Consumer loans,3951.000,24835.5,23787.0,2520.0,24835.5,FRIDAY,13,...,Connectivity,8.0,high,POS mobile with interest,365243.0,-1709.0,-1499.0,-1619.0,-1612.0,0.0
892077,1038818,100002,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,...,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
575941,1810518,100003,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
1021650,2636178,100003,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,...,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
1223745,2396755,100003,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,...,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411592,2729207,456255,Consumer loans,11514.555,58225.5,58545.0,5823.0,58225.5,FRIDAY,18,...,Connectivity,6.0,high,POS mobile with interest,365243.0,-469.0,-319.0,-409.0,-400.0,0.0
608510,2073384,456255,Cash loans,16400.610,229500.0,254340.0,NaN,229500.0,THURSDAY,12,...,XNA,24.0,middle,Cash X-Sell: middle,365243.0,-618.0,72.0,-558.0,-528.0,1.0
596623,1179690,456255,Cash loans,28873.170,450000.0,491580.0,NaN,450000.0,TUESDAY,13,...,XNA,24.0,middle,Cash X-Sell: middle,365243.0,-662.0,28.0,-212.0,-204.0,1.0
1383554,2631384,456255,Cash loans,54022.140,1170000.0,1271929.5,NaN,1170000.0,FRIDAY,14,...,XNA,36.0,low_normal,Cash X-Sell: low,365243.0,-756.0,294.0,-66.0,-64.0,0.0
214743,1743609,456255,Consumer loans,11090.835,102037.5,112815.0,0.0,102037.5,THURSDAY,18,...,Furniture,12.0,middle,POS industry with interest,365243.0,-960.0,-630.0,-690.0,-687.0,0.0

In [24]:
PrevLoans.loc[PrevLoans['DAYS_FIRST_DRAWING']==365243, 'DAYS_FIRST_DRAWING'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_FIRST_DUE']==365243, 'DAYS_FIRST_DUE'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_LAST_DUE_1ST_VERSION']==365243, 'DAYS_LAST_DUE_1ST_VERSION'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_LAST_DUE']==365243, 'DAYS_LAST_DUE'] = np.nan
PrevLoans.loc[PrevLoans['DAYS_TERMINATION']==365243, 'DAYS_TERMINATION'] = np.nan

In [25]:
PrevLoans.head(25)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
201668,1369693,100001,Consumer loans,3951.000,24835.50,23787.0,2520.00,24835.50,FRIDAY,13,...,Connectivity,8.0,high,POS mobile with interest,NaN,-1709.0,-1499.0,-1619.0,-1612.0,0.0
892077,1038818,100002,Consumer loans,9251.775,179055.00,179055.0,0.00,179055.00,SATURDAY,9,...,Auto technology,24.0,low_normal,POS other with interest,NaN,-565.0,125.0,-25.0,-17.0,0.0
575941,1810518,100003,Cash loans,98356.995,900000.00,1035882.0,NaN,900000.00,FRIDAY,12,...,XNA,12.0,low_normal,Cash X-Sell: low,NaN,-716.0,-386.0,-536.0,-527.0,1.0
1021650,2636178,100003,Consumer loans,64567.665,337500.00,348637.5,0.00,337500.00,SUNDAY,17,...,Furniture,6.0,middle,POS industry with interest,NaN,-797.0,-647.0,-647.0,-639.0,0.0
1223745,2396755,100003,Consumer loans,6737.310,68809.50,68053.5,6885.00,68809.50,SATURDAY,15,...,Consumer electronics,12.0,middle,POS household with interest,NaN,-2310.0,-1980.0,-1980.0,-1976.0,1.0
935548,1564014,100004,Consumer loans,5357.250,24282.00,20106.0,4860.00,24282.00,FRIDAY,5,...,Connectivity,4.0,middle,POS mobile without interest,NaN,-784.0,-694.0,-724.0,-714.0,0.0
1259112,1857999,100005,Cash loans,NaN,0.00,0.0,NaN,NaN,FRIDAY,10,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1378978,2495675,100005,Consumer loans,4813.200,44617.50,40153.5,4464.00,44617.50,THURSDAY,11,...,Connectivity,12.0,high,POS mobile with interest,NaN,-706.0,-376.0,-466.0,-460.0,0.0
98162,2078043,100006,Cash loans,24246.000,675000.00,675000.0,NaN,675000.00,THURSDAY,15,...,XNA,48.0,low_normal,Cash X-Sell: low,NaN,-151.0,1259.0,-151.0,-143.0,0.0
617859,2827850,100006,Revolving loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
900957,1489396,100006,Revolving loans,13500.000,270000.00,270000.0,NaN,270000.00,THURSDAY,15,...,XNA,0.0,XNA,Card X-Sell,NaN,NaN,NaN,NaN,NaN,0.0
1232752,1243599,100006,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1595430,2545789,100006,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1607443,1697039,100006,Cash loans,32696.100,688500.00,906615.0,NaN,688500.00,THURSDAY,15,...,XNA,48.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
830967,2190416,100006,Consumer loans,29027.520,334917.00,267930.0,66987.00,334917.00,SUNDAY,15,...,Consumer electronics,12.0,high,POS household with interest,NaN,-281.0,49.0,NaN,NaN,0.0
1131133,1020698,100006,Cash loans,39954.510,454500.00,481495.5,NaN,454500.00,SATURDAY,12,...,XNA,18.0,high,Cash X-Sell: high,NaN,NaN,NaN,NaN,NaN,NaN
1333657,2299329,100006,Consumer loans,2482.920,26912.34,24219.0,2693.34,26912.34,TUESDAY,15,...,Construction,12.0,middle,POS industry with interest,NaN,-545.0,-215.0,-425.0,-416.0,0.0
693308,1692033,100007,Cash loans,16037.640,247500.00,274288.5,NaN,247500.00,MONDAY,11,...,XNA,24.0,middle,Cash X-Sell: middle,NaN,-344.0,346.0,NaN,NaN,1.0
13392,2001242,100007,Cash loans,16509.600,180000.00,180000.0,NaN,180000.00,SUNDAY,14,...,Consumer electronics,18.0,high,Cash Street: high,NaN,-834.0,-324.0,-354.0,-347.0,0.0
87569,2730157,100007,Cash loans,13010.985,225000.00,284400.0,NaN,225000.00,FRIDAY,13,...,XNA,48.0,middle,Cash X-Sell: middle,NaN,NaN,NaN,NaN,NaN,NaN
1483068,1940724,100007,Cash loans,22678.785,202500.00,215865.0,NaN,202500.00,THURSDAY,8,...,Consumer electronics,12.0,middle,Cash X-Sell: middle,NaN,-1076.0,-746.0,-746.0,-739.0,1.0
1260339,2462742,100007,Consumer loans,3601.530,31005.00,30663.0,3105.00,31005.00,SUNDAY,15,...,Connectivity,12.0,high,POS mobile with interest,NaN,-1736.0,-1406.0,-1406.0,-1397.0,0.0
1061094,2119973,100007,Consumer loans,1834.290,17176.50,14616.0,3676.50,17176.50,SATURDAY,13,...,Consumer electronics,10.0,high,POS household with interest,NaN,-2326.0,-2056.0,-2056.0,-2041.0,1.0
600145,1757431,100008,Cash loans,NaN,0.00,0.0,NaN,NaN,FRIDAY,18,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
320227,2218188,100008,Consumer loans,17885.835,162598.50,162598.5,0.00,162598.50,THURSDAY,10,...,Consumer electronics,10.0,low_normal,POS household with interest,NaN,-339.0,-69.0,-69.0,-66.0,0.0

In [26]:
PrevLoans['NAME_PAYMENT_TYPE'].value_counts(dropna=False)

NAME_PAYMENT_TYPE
Cash through the bank                        1033552
XNA                                           627384
Non-cash from your account                      8193
Cashless from the account of the employer       1085
Name: count, dtype: int64

In [27]:
PrevLoans[PrevLoans['NAME_PAYMENT_TYPE']=='XNA']

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
892077,1038818,100002,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,...,Auto technology,24.0,low_normal,POS other with interest,NaN,-565.0,125.0,-25.0,-17.0,0.0
575941,1810518,100003,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,...,XNA,12.0,low_normal,Cash X-Sell: low,NaN,-716.0,-386.0,-536.0,-527.0,1.0
1259112,1857999,100005,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,10,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
617859,2827850,100006,Revolving loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,15,...,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
900957,1489396,100006,Revolving loans,13500.000,270000.0,270000.0,NaN,270000.0,THURSDAY,15,...,XNA,0.0,XNA,Card X-Sell,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345759,2624169,456250,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,8,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
553648,1511244,456250,Cash loans,NaN,0.0,0.0,NaN,NaN,THURSDAY,7,...,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1467403,1740566,456250,Cash loans,26474.625,225000.0,239850.0,NaN,225000.0,MONDAY,4,...,XNA,12.0,high,Cash X-Sell: high,NaN,-707.0,-377.0,-377.0,-374.0,1.0
791939,1922117,456250,Consumer loans,26084.430,141570.0,147645.0,0.0,141570.0,FRIDAY,5,...,Consumer electronics,6.0,low_normal,POS household with interest,NaN,-1038.0,-888.0,-888.0,-884.0,0.0
729432,1708056,456255,Revolving loans,2250.000,45000.0,45000.0,NaN,45000.0,SUNDAY,14,...,Connectivity,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
PrevLoans[PrevLoans['DAYS_FIRST_DRAWING'].isna()]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
201668,1369693,100001,Consumer loans,3951.000,24835.5,23787.0,2520.0,24835.5,FRIDAY,13,...,Connectivity,8.0,high,POS mobile with interest,NaN,-1709.0,-1499.0,-1619.0,-1612.0,0.0
892077,1038818,100002,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,...,Auto technology,24.0,low_normal,POS other with interest,NaN,-565.0,125.0,-25.0,-17.0,0.0
575941,1810518,100003,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,...,XNA,12.0,low_normal,Cash X-Sell: low,NaN,-716.0,-386.0,-536.0,-527.0,1.0
1021650,2636178,100003,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,...,Furniture,6.0,middle,POS industry with interest,NaN,-797.0,-647.0,-647.0,-639.0,0.0
1223745,2396755,100003,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,...,Consumer electronics,12.0,middle,POS household with interest,NaN,-2310.0,-1980.0,-1980.0,-1976.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411592,2729207,456255,Consumer loans,11514.555,58225.5,58545.0,5823.0,58225.5,FRIDAY,18,...,Connectivity,6.0,high,POS mobile with interest,NaN,-469.0,-319.0,-409.0,-400.0,0.0
608510,2073384,456255,Cash loans,16400.610,229500.0,254340.0,NaN,229500.0,THURSDAY,12,...,XNA,24.0,middle,Cash X-Sell: middle,NaN,-618.0,72.0,-558.0,-528.0,1.0
596623,1179690,456255,Cash loans,28873.170,450000.0,491580.0,NaN,450000.0,TUESDAY,13,...,XNA,24.0,middle,Cash X-Sell: middle,NaN,-662.0,28.0,-212.0,-204.0,1.0
1383554,2631384,456255,Cash loans,54022.140,1170000.0,1271929.5,NaN,1170000.0,FRIDAY,14,...,XNA,36.0,low_normal,Cash X-Sell: low,NaN,-756.0,294.0,-66.0,-64.0,0.0
214743,1743609,456255,Consumer loans,11090.835,102037.5,112815.0,0.0,102037.5,THURSDAY,18,...,Furniture,12.0,middle,POS industry with interest,NaN,-960.0,-630.0,-690.0,-687.0,0.0

In [29]:
PrevLoans['PRODUCT_COMBINATION'].value_counts(dropna=False)

PRODUCT_COMBINATION
Cash                              285990
POS household with interest       263622
POS mobile with interest          220670
Cash X-Sell: middle               143883
Cash X-Sell: low                  130248
Card Street                       112582
POS industry with interest         98833
POS household without interest     82908
Card X-Sell                        80582
Cash Street: high                  59639
Cash X-Sell: high                  59301
Cash Street: middle                34658
Cash Street: low                   33834
POS mobile without interest        24082
POS other with interest            23879
POS industry without interest      12602
POS others without interest         2555
NaN                                  346
Name: count, dtype: int64

In [30]:
PrevLoans['DAYS_LAST_DUE'].notna().sum()

np.int64(785928)

In [31]:
PrevLoans['DAYS_DECISION'].notna().sum()

np.int64(1670214)

In [32]:
PrevLoans['RATE_INTEREST_PRIVILEGED'].isna().sum()

np.int64(1664263)

In [33]:
PrevLoans['CREDIT_TO_APPL'] = np.where( PrevLoans['AMT_APPLICATION'] > 0,
            PrevLoans['AMT_CREDIT'] / PrevLoans['AMT_APPLICATION'],
            np.nan)

PrevLoans['GOODSPRICE_TO_AMT'] = np.where( PrevLoans['AMT_APPLICATION'] > 0,
            PrevLoans['AMT_GOODS_PRICE'] / PrevLoans['AMT_APPLICATION'],
            np.nan)

In [34]:
PrevLoans['RATE_INTEREST_PRIMARY'].isna().sum()

np.int64(1664263)

In [35]:
ApprovedLoans = PrevLoans[~ (PrevLoans['NAME_CONTRACT_STATUS'] == 'Refused')]
RefusedLoans  = PrevLoans[PrevLoans['NAME_CONTRACT_STATUS'] == 'Refused']

In [36]:
RefusedLoans_Silver = RefusedLoans.groupby('SK_ID_CURR').agg(
    PREVIOUS_LOAN_REFUSED_COUNT = ('NAME_CONTRACT_STATUS',lambda x: sum(x=='Refused')),
    PREVIOUS_LOAN_REFUSED_AVG_LOAN_AMOUNT = ('AMT_CREDIT','mean'),
    PREVIOUS_LOAN_REFUSED_AVG_GOODS_TO_AMT_RATIO = ('GOODSPRICE_TO_AMT','mean'),
    PREVIOUS_LOAN_REFUSED_LASTYEAR_COUNT = ('DAYS_DECISION', lambda x: sum(x > -365)),
    PREVIOUS_LOAN_LAST_REFUSED_DAY = ('DAYS_DECISION', 'max'),
    PREVIOUS_LOAN_REFUSED_MULTIPLE_ATTEMPTS_COUNT = ('FLAG_LAST_APPL_PER_CONTRACT', lambda x: sum(x == 'N'))
)

In [37]:
def get_last_approved(x, full_df):
    approved = full_df.loc[x.index, 'NAME_CONTRACT_STATUS'] == 'Approved'
    return x[approved].iloc[0] if approved.any() else np.nan

In [38]:
ApprovedLoans_Silver = ApprovedLoans.groupby('SK_ID_CURR').agg(

    PREVIOUS_LOAN_APPROVED_COUNT = ('NAME_CONTRACT_STATUS',lambda x: sum(x=='Approved')),
    PREVIOUS_LOAN_CANCELED_COUNT = ('NAME_CONTRACT_STATUS',lambda x: sum(x=='Canceled')),
    
    PREVIOUS_LOAN_AVG_AMOUNT = ('AMT_CREDIT','mean'),
    PREVIOUS_LOAN_MAX_AMOUNT = ('AMT_CREDIT','max'),
    PREVIOUS_LOAN_TERM_AVG = ('CNT_PAYMENT','mean'),
    PREVIOUS_LOAN_TERM_MAX = ('CNT_PAYMENT','max'),

    PREVIOUS_LOAN_AVG_DOWNPAYMENT_AMOUNT = ('AMT_DOWN_PAYMENT','mean'),
    PREVIOUS_LOAN_AVG_DOWNPAYMENT_RATIO = ('RATE_DOWN_PAYMENT','mean'),
    PREVIOUS_LOAN_AVG_CREDIT_TO_APPLIED_RATIO = ('CREDIT_TO_APPL', 'mean'),

    PREVIOUS_LOAN_NUM_OF_HIGHYIELD_LOANS = ('NAME_YIELD_GROUP', lambda x: sum(x == 'high')),

    PREVIOUS_LOAN_NUM_OF_CASHLOANS = ('NAME_CONTRACT_TYPE', lambda x: sum(x == 'Cash loans')),
    PREVIOUS_LOAN_NUM_OF_CONSUMERLOANS = ('NAME_CONTRACT_TYPE', lambda x: sum(x == 'Consumer loans')),
    PREVIOUS_LOAN_NUM_OF_REVOLVINGLOANS = ('NAME_CONTRACT_TYPE', lambda x: sum(x == 'Revolving loans')),
    
    PREVIOUS_LOAN_NUM_OF_HIGHRISK_CHANNELS = ('CHANNEL_TYPE', lambda x: sum( (x == 'AP+ (Cash loan)') | (x == 'Car dealer'))),

    PREVIOUS_LOAN_INSURANCE_REQUESTED = ('NFLAG_INSURED_ON_APPROVAL','max'),
    PREVIOUS_LOAN_NUM_OF_INSURANCE = ('NFLAG_INSURED_ON_APPROVAL','count'),

    PREVIOUS_LOAN_DAYS_BETWEEN_LOANS=('DAYS_DECISION', lambda x: x.diff().mean()),
    PREVIOUS_LOAN_DAYS_LAST_APPROVED=('DAYS_DECISION', lambda x: get_last_approved(x, ApprovedLoans)),
    PREVIOUS_LOAN_LAST_LOAN_STATUS=('NAME_CONTRACT_STATUS', 'last'),
    PREVIOUS_LOAN_MULTIPLE_ATTEMPTS_COUNT=('FLAG_LAST_APPL_PER_CONTRACT', lambda x: sum(x == 'N'))
)

In [39]:
PrevLoans_Silver = PrevLoans.groupby('SK_ID_CURR').agg(
    PREVIOUS_LOAN_APPL_COUNT = ('SK_ID_PREV','count')
    ).merge(
        ApprovedLoans_Silver,
        on='SK_ID_CURR',
        how='left'
    ).merge(
        RefusedLoans_Silver,
        on='SK_ID_CURR',
        how='left'
    )

In [40]:
PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_COUNT'].fillna(0, inplace=True)
PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_AVG_LOAN_AMOUNT'].fillna(0, inplace=True) 
PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_AVG_GOODS_TO_AMT_RATIO'].fillna(0, inplace=True)
PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_LASTYEAR_COUNT'].fillna(0, inplace=True)
#PrevLoans_Silver['PREVIOUS_LOAN_LAST_REFUSED_DAY'].fillna(10000 inplace=True)
PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_MULTIPLE_ATTEMPTS_COUNT'].fillna(0, inplace=True)

C:\Users\domjo\AppData\Local\Temp\ipykernel_23148\215182425.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_COUNT'].fillna(0, inplace=True)
C:\Users\domjo\AppData\Local\Temp\ipykernel_23148\215182425.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_AVG_LOAN_AMOUNT'].fillna(0, inplace=True)
C:\Users\domjo\AppData\Local\Temp\ipykernel_23148\215182425.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_AVG_GOODS_TO_AMT_RATIO'].fillna(0, inplace=True)
C:\Users\domjo\AppData\Local\Temp\ipykernel_23148\215182425.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_LASTYEAR_COUNT'].fillna(0, inplace=True)
C:\Users\domjo\AppData\Local\Temp\ipykernel_23148\215182425.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  PrevLoans_Silver['PREVIOUS_LOAN_REFUSED_MULTIPLE_ATTEMPTS_COUNT'].fillna(0, inplace=True)

`PREVIOUS_LOAN_LAST_REFUSED_DAY` should have separate category for nans. So do `PREVIOUS_LOAN_DAYS_BETWEEN_LOANS`

In [41]:
PrevLoans_Silver.to_parquet("a:\\Dominic\\My Projects\\Home Credit\\src\\intermediate\\prev_loandata_processed.parquet")